Homework lesson 03
Desto333/FreeIT pull request #1
Opened 2020-07-23 12:04 UTC by Desto333

Lesson 3 homework is done.

2020-07-24 15:46 UTC, RomanKashenok requested changes
Надо бы доработать

2020-07-24 15:46 UTC, RomanKashenok commented on lesson_03/Lesson03_Task13_met.java
> +        for (int start = 0; start < arr.length; start++) {          // сортируем массив по возрастанию
что бы найти максимальное число не нужно сортровать массив. По нему достаточно один раз пройтись

2020-07-24 15:46 UTC, RomanKashenok commented on lesson_03/Lesson03_Task14_met.java
> +        for (int start = 0; start < arrCopy.length; start++) {          // сортируем копию массива по возрастанию
Сортируя таким образом созданный массив ( я про копию) ты сортируешь и исходный
Так что у тебя всегда будет минимальное на позиции 0, а максиамальное на 19й


Lesson03_Task16_met - вот тут ты правильно делаешь

2020-07-24 15:46 UTC, RomanKashenok commented on lesson_03/Lesson03_Task17_met.java
> +        for (int i = 0; i < arr.length; i++) {          // проходимся двойным циклом по всем элементам, нужные ячейки заполняем 0
При размерности матрисы не 5 х 5 не будет работать, а должно

2020-07-25 06:23 UTC, Desto333 commented on lesson_03/Lesson03_Task13_met.java
> +        for (int start = 0; start < arr.length; start++) {          // сортируем массив по возрастанию
исправил поиск наибольшего числа

2020-07-25 06:27 UTC, Desto333 commented on lesson_03/Lesson03_Task14_met.java
> +        for (int start = 0; start < arrCopy.length; start++) {          // сортируем копию массива по возрастанию
также переделал поиск максимума и минимума, переделал вывод  их индекса (или индексов)

2020-07-26 12:53 UTC, RomanKashenok approved these changes

2020-07-26 19:42 UTC, merged