Homework lesson10
Desto333/FreeIT pull request #6
Opened 2020-09-05 13:15 UTC by Desto333

2020-09-07 08:16 UTC, RomanKashenok requested changes

2020-09-07 08:16 UTC, RomanKashenok commented on lesson_10/Lesson10_Task29_met.java
> +        System.out.println();
Just to note.
You can print all List elements with sout(Arrays.toString(<yur array>))

2020-09-07 08:16 UTC, RomanKashenok commented on lesson_10/Lesson10_Task32_met.java
> +        for (int i = 0; i < list.size(); i++) {                                                 // go through all the words in ArrayList, count repeatings and save the result to our frequency vocabul
It's too expensive operation - for every word start two cycles. It's better to do it with only one cycle and using HashMap put on every word occurrence (just check if word already in map - add 1 to value, if not - create new key-value)

2020-09-07 08:16 UTC, RomanKashenok commented on lesson_10/Library_add/Book.java
> +    private String bookGenre;   // как сделать как в задании методички? чтобы по указанию genreId вызывался соответствующий объект Genre
use Genre instead of String for bookGenre field

2020-09-07 08:16 UTC, RomanKashenok commented on lesson_10/Library_add/Library.java
> +                System.out.println("Ошибка! ID должен быть уникальным, такой id уже существует!");
You should to generate ID automatically to prevent suck kink of exceptions

2020-09-07 08:16 UTC, RomanKashenok commented on lesson_10/Library_add/Menu.java
> +        while (true) {
Use please some flag for user to be able to close programm

2020-09-07 08:16 UTC, RomanKashenok commented on lesson_10/Library_main/Book.java
> +    private String bookGenre;   // как сделать как в задании методички? чтобы по указанию genreId вызывался соответствующий объект Genre
// как сделать как в задании методички? чтобы по указанию genreId вызывался соответствующий объект Genre

for that purpose you can implement your own logic. But not here - somewhere in Library class. Better just to use Genre type for that field

2020-09-13 10:21 UTC, TheFallen058 approved these changes
small notes from my side

2020-09-13 10:21 UTC, TheFallen058 commented on lesson_10/Library_main/Main.java
> +    public static void main(String[] args) throws NoSuchMethodException {
surplus throws error

2020-09-13 10:21 UTC, TheFallen058 commented on lesson_10/Library_add/Library.java
> +                System.out.println("Ошибка! ID должен быть уникальным, такой id уже существует!");
After error
Ошибка! ID должен быть уникальным, такой id уже существует!
I can proceed to edit the book, incorrect logic

2020-09-13 10:21 UTC, TheFallen058 commented on lesson_10/Library_add/Library.java
> +                System.out.println("Ошибка! ID должен быть уникальным, такой id уже существует!");
in case it's just edit of the book id should be left the same

2020-09-19 22:11 UTC, Desto333 commented
Made requested changes both to homework 9 and 10. Please, review.

2020-10-04 17:03 UTC, merged